apiVersion: apps/v1
kind: Deployment
metadata:
  name: novix-playground
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: web
        image: novix-web:latest
        ports: [ { containerPort: 3000 } ]
        envFrom:
        - configMapRef: { name: novix-config }
