version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web-ui:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
    volumes:
      - ./api:/app
    expose:
      - "8000"

  novix:
    image: ainovix/novix:latest
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - "3437"

networks:
  default:
    driver: bridge
