apiVersion: apps/v1
kind: Deployment
metadata:
  name: novix-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: novix
  template:
    metadata:
      labels:
        app: novix
    spec:
      containers:
      - name: api
        image: novix-api:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: novix-secrets

      - name: web
        image: novix-web:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: novix-service
spec:
  selector:
    app: novix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novix-ingress
spec:
  rules:
  - host: novix.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: novix-service
            port:
              number: 80
