name: Deploy API
on:
  push:
    branches: [main]
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        run: |
          cd api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/novix-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/novix-api:latest
