name: Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Here we define what to include and exclude for the artifact upload
          path: 'docs'
          # If you want to exclude specific files or directories:
          exclude: |
            docs/node_modules/**
            docs/.gitignore

      - name: Deploy
        uses: actions/deploy-pages@v4
