name: Deploy Docs

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'package*.json' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: |
          npm install
          npm install showdown prismjs
          
      - name: Build Docs
        run: node docs/build.js
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
